#  RecruitAI Assistant

### AI-Powered Resume Repository Search for Recruiters

### Problem Statement

Recruiters often store resumes in local folders. When a similar requirement arrives, they manually search through hundreds of resumes or source candidates again from job portals.

This application helps recruiters search their existing resume repository using AI and find the best matching candidates for a Job Description.

---

### Tech Stack

- Python
- Google Colab
- PyMuPDF
- Sentence Transformers
- Scikit-learn
- Pandas
- Gradio

# Install Libraries

In [2]:
!pip install pymupdf
!pip install pandas
!pip install sentence-transformers
!pip install scikit-learn

Collecting pymupdf
  Downloading pymupdf-1.28.0-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (26 kB)
Downloading pymupdf-1.28.0-cp310-abi3-manylinux_2_28_x86_64.whl (25.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.7/25.7 MB 91.6 MB/s eta 0:00:00
Installing collected packages: pymupdf
Successfully installed pymupdf-1.28.0
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.13.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.23.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

# Import Libraries

In [3]:
import os
import fitz  # PyMuPDF
import pandas as pd

In [4]:
from google.colab import files
uploaded = files.upload()

Saving DHAIRYAKANT R HARSORA Resume-2.pdf to DHAIRYAKANT R HARSORA Resume-2.pdf

# Function to Read PDF

In [5]:
import fitz  # PyMuPDF

def extract_text_from_pdf(pdf_path):
    """
    Extract text from a PDF file.
    """

    document = fitz.open(pdf_path)

    text = ""

    for page in document:
        text += page.get_text()

    document.close()

    return text

# Test on One Resume

In [6]:
sample_resume = os.path.join(
    "/content/MANSI GURAV Resumepdf.pdf"
)

resume_text = extract_text_from_pdf(sample_resume)

print(resume_text[:2000])

C o m p u t e r S c i e n c e E n g i n e e r i n g
s t u d e n t
M A N S I G U R A V
E D U C A T I O N
M.S. Gosavi polytechnic
institute Nashik
2020-2023
S K I L L S
Full Stack Development
(ASP.NET)
HTML, CSS, JAVASCRIPT,React
Python
UI/UX Design (Figma)
Graphic Designing (Basic)
Canva
Android Development (Basic)
Flutter (Basic)
P R O J E C T S
Dyslexia Screening System using Fuzzy Logic |Python,
Tkinter, Scikit-Fuzzy
ROLES & RESPONSIBILITIES:
P R O F I L E
Computer Science Engineering student with knowledge of
ASP.NET full-stack development, Android application
development, and UI/UX design using Figma. Skilled in
building simple and user-friendly applications with
experience in Java, HTML, and Firebase. Eager to apply
technical skills, learn new technologies, and gain practical
industry experience in software development.
+91 842-101-6207
 Nashik, Maharashtra-422401
mgurav2412@gmail.com
C E R T I F I C A T I O N S
Full Stack Web Development
using ASP.NET (.NET)
Designathon Participation
Certificate – ITM University,
Vadodara (2026)
Python Programming-Homeflic
Wegrow (Dec 2021)
Diploma in Computer science
C O N T A C T
Developed a smart system to analyze typing
performance and predict dyslexia risk using fuzzy logic.
Evaluated user typing speed and accuracy to assess
potential learning difficulties.
Designed and implemented fuzzy logic rules for
intelligent risk classification.
Built an interactive GUI using Tkinter for user-friendly
data input and result display.
Visualized analysis results using graphs for better
interpretation and insights.
ITM (SLS) BARODA UNIVERSITY
2024-2027
B.Tech Computer Science
Engineering student
VisaEase – Travel Booking Web Application | React.js,
Node.js, MySQL
ROLES & RESPONSIBILITIES:
Developed a travel booking website to explore
destinations and book travel packages.
Implemented user authentication including login,
signup, and password recovery.
 Built booking system and user dashboard to manage
bookings and travel history.
Integ

# Read ALL Resumes

In [7]:
resume_files = [f for f in os.listdir() if f.endswith(".pdf")]

In [8]:
resume_data = []

for file in resume_files:

    pdf_path = file

    text = extract_text_from_pdf(pdf_path)

    resume_data.append({
        "Candidate": file,
        "Resume_Text": text
    })

print("Total resumes processed:", len(resume_data))

Total resumes processed: 5

# Convert to DataFrame

In [9]:
resume_df = pd.DataFrame(resume_data)

resume_df.head()

,Candidate,Resume_Text
0,Raja_Kullai_Resume.pdf,\nBIM MEP Modeller \n✉ dudekulachinnakulai@gm...
1,Parth Maru CV.pdf,CONTACT\nSeptember 2025 -\nDecember 2025\nJune...
2,A_Priya.pdf,Page 1 of 3 \n \nPriya A \n +91 9344481662 \n ...
3,DHAIRYAKANT R HARSORA Resume-2.pdf,P R O J E C T S :\nS U M M A R Y :\nE D U C A ...
4,MANSI GURAV Resumepdf.pdf,C o m p u t e r S c i e n c e E n g i n e e r ...

# Load Job Descriptions

# Read One JD

In [10]:
def read_job_description(file_path):

    with open(file_path, "r", encoding="utf-8") as file:
        text = file.read()

    return text

# List all JDs

In [11]:
jd_files = [f for f in os.listdir() if f.endswith(".txt")]

print("Total Job Descriptions:", len(jd_files))
print()

for jd in jd_files:
    print(jd)

Total Job Descriptions: 5

BIM_MEP_Modeller.txt
cyber_security_Intern.txt
SEO_Executive.txt
Transport_Executive.txt
Full_Stack_Developer_Intern.txt

In [12]:
for jd in jd_files:
    print("=" * 50)
    print("Job:", jd)
    print("=" * 50)

    with open(jd, "r", encoding="utf-8") as f:
        text = f.read()

    print(text[:500])   # Print first 500 characters
    print()

==================================================
Job: BIM_MEP_Modeller.txt
==================================================
===================================================
JOB DESCRIPTION
===================================================

Job Title:
BIM MEP Modeller

Department:
Engineering

Location:
Bengaluru

Employment Type:
Full Time

Experience Required:
2-4 Years

Education:
Diploma/B.Tech Mechanical Engineering

Required Skills:
- Revit MEP
- AutoCAD
- Navisworks
- HVAC
- Plumbing
- Fire Fighting
- Clash Detection

Preferred Skills:
- Autodesk ReCap
- Shop Drawings

Responsibilities:
- Develop BIM MEP m

==================================================
Job: cyber_security_Intern.txt
==================================================
===================================================
JOB DESCRIPTION
===================================================

Job Title:
Cyber Security Intern

Department:
Cyber Security

Location:
Ahmedabad

Employment Type:
Internship

Experience Required:
0-1 Years

Education:
B.Tech/B.E. in Computer Science, Information Technology, Cyber Security or related field.

Required Skills:
- Python
- Networking Fundamentals
- Cyber Security
- Intrusion Detection Systems (IDS)
- Machine Learning Basics
-

==================================================
Job: SEO_Executive.txt
==================================================
===================================================
JOB DESCRIPTION
===================================================

Job Title:
SEO Executive

Department:
Digital Marketing

Location:
Ahmedabad

Employment Type:
Full Time

Experience Required:
1-2 Years

Education:
Graduate in any discipline.

Required Skills:
- Keyword Research
- On-Page SEO
- Off-Page SEO
- Technical SEO
- Google Analytics
- SEO Reporting
- Content Optimization

Preferred Skills:
- Schema Markup
- AEO
- AI Search Optimizat

==================================================
Job: Transport_Executive.txt
==================================================
===================================================
JOB DESCRIPTION
===================================================

Job Title:
Transport Executive

Department:
Logistics / Supply Chain

Location:
Mumbai

Employment Type:
Full Time

Experience Required:
2-5 Years

Education:
Bachelor's Degree in Logistics, Supply Chain Management, Commerce, Business Administration, or a related field.

Required Skills:
- Transportation Management
- Logistics Coordination
- Import & Export Documentation
- Cus

==================================================
Job: Full_Stack_Developer_Intern.txt
==================================================
===================================================
JOB DESCRIPTION
===================================================

Job Title:
Full Stack Developer Intern

Department:
Software Development

Location:
Vadodara

Employment Type:
Internship

Experience Required:
0-1 Years

Education:
B.Tech/B.E. Computer Science

Required Skills:
- ASP.NET
- HTML
- CSS
- JavaScript
- React
- Python
- MySQL
- Firebase

Preferred Skills:
- Flutter
- Figma

Responsibilities:
- Build responsive web applications.
-

# Read all Job Descriptions into a dictionary

In [13]:
jd_data = {}

for jd in jd_files:
    with open(jd, "r", encoding="utf-8") as f:
        jd_data[jd] = f.read()

print("Loaded", len(jd_data), "Job Descriptions")

Loaded 5 Job Descriptions

In [14]:
for name, content in jd_data.items():
    print("=" * 70)
    print("Job Title:", name)
    print("=" * 70)
    print(content[:500])      # First 500 characters
    print("\n")

======================================================================
Job Title: BIM_MEP_Modeller.txt
======================================================================
===================================================
JOB DESCRIPTION
===================================================

Job Title:
BIM MEP Modeller

Department:
Engineering

Location:
Bengaluru

Employment Type:
Full Time

Experience Required:
2-4 Years

Education:
Diploma/B.Tech Mechanical Engineering

Required Skills:
- Revit MEP
- AutoCAD
- Navisworks
- HVAC
- Plumbing
- Fire Fighting
- Clash Detection

Preferred Skills:
- Autodesk ReCap
- Shop Drawings

Responsibilities:
- Develop BIM MEP m


======================================================================
Job Title: cyber_security_Intern.txt
======================================================================
===================================================
JOB DESCRIPTION
===================================================

Job Title:
Cyber Security Intern

Department:
Cyber Security

Location:
Ahmedabad

Employment Type:
Internship

Experience Required:
0-1 Years

Education:
B.Tech/B.E. in Computer Science, Information Technology, Cyber Security or related field.

Required Skills:
- Python
- Networking Fundamentals
- Cyber Security
- Intrusion Detection Systems (IDS)
- Machine Learning Basics
-


======================================================================
Job Title: SEO_Executive.txt
======================================================================
===================================================
JOB DESCRIPTION
===================================================

Job Title:
SEO Executive

Department:
Digital Marketing

Location:
Ahmedabad

Employment Type:
Full Time

Experience Required:
1-2 Years

Education:
Graduate in any discipline.

Required Skills:
- Keyword Research
- On-Page SEO
- Off-Page SEO
- Technical SEO
- Google Analytics
- SEO Reporting
- Content Optimization

Preferred Skills:
- Schema Markup
- AEO
- AI Search Optimizat


======================================================================
Job Title: Transport_Executive.txt
======================================================================
===================================================
JOB DESCRIPTION
===================================================

Job Title:
Transport Executive

Department:
Logistics / Supply Chain

Location:
Mumbai

Employment Type:
Full Time

Experience Required:
2-5 Years

Education:
Bachelor's Degree in Logistics, Supply Chain Management, Commerce, Business Administration, or a related field.

Required Skills:
- Transportation Management
- Logistics Coordination
- Import & Export Documentation
- Cus


======================================================================
Job Title: Full_Stack_Developer_Intern.txt
======================================================================
===================================================
JOB DESCRIPTION
===================================================

Job Title:
Full Stack Developer Intern

Department:
Software Development

Location:
Vadodara

Employment Type:
Internship

Experience Required:
0-1 Years

Education:
B.Tech/B.E. Computer Science

Required Skills:
- ASP.NET
- HTML
- CSS
- JavaScript
- React
- Python
- MySQL
- Firebase

Preferred Skills:
- Flutter
- Figma

Responsibilities:
- Build responsive web applications.
-

# Install required libraries

In [15]:
!pip install pymupdf sentence-transformers scikit-learn -q

# Import libraries

In [16]:
import fitz  # PyMuPDF
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# Read the Resume PDF

In [17]:
resume_files = [f for f in os.listdir() if f.endswith(".pdf")]

In [18]:
import fitz
import os

resume_files = [f for f in os.listdir() if f.endswith(".pdf")]

print(resume_files)

resume_file = resume_files[0]   # Opens the first PDF

doc = fitz.open(resume_file)

resume_text = ""

for page in doc:
    resume_text += page.get_text()

doc.close()

print(resume_text[:1000])

['Raja_Kullai_Resume.pdf', 'Parth Maru CV.pdf', 'A_Priya.pdf', 'DHAIRYAKANT R HARSORA Resume-2.pdf', 'MANSI GURAV Resumepdf.pdf']

BIM MEP Modeller
✉ dudekulachinnakulai@gmail.com






☎ +91 8179118652

               Professional MEP Engineer with 3 years of experience in MEP modelling for residential and
commercial projects. Skilled in developing detailed HVAC, plumbing, firefighting, and electrical models using
industry-standard software. Experienced in preparing shop drawings, clash-free coordinated models, and
ensuring compliance with project standards and specifications. Dedicated to delivering high-quality work with
strong technical, analytical, and problem-solving skills.

• Yashoda Hospital Expansion – Hospital Project @ Hyderabad, India
• Kempegowda International Airport – T2 MEP Modelling Project @ Bengaluru, India

• GreenKo Group




   GET- PMC
             Hyderabad - India




   Feb 2025 – May 2025
• Magnasoft Consulting india                                          Trainee Engineer
 pvt ltd

In [19]:
import fitz
import os

resume_files = [f for f in os.listdir() if f.endswith(".pdf")]

for resume_file in resume_files:
    print("=" * 50)
    print("Processing:", resume_file)

    doc = fitz.open(resume_file)

    text = ""
    for page in doc:
        text += page.get_text()

    doc.close()

    print(text[:500])

==================================================
Processing: Raja_Kullai_Resume.pdf

BIM MEP Modeller
✉ dudekulachinnakulai@gmail.com






☎ +91 8179118652

               Professional MEP Engineer with 3 years of experience in MEP modelling for residential and
commercial projects. Skilled in developing detailed HVAC, plumbing, firefighting, and electrical models using
industry-standard software. Experienced in preparing shop drawings, clash-free coordinated models, and
ensuring compliance with project standards and specifications. Dedicated to delivering high-q
==================================================
Processing: Parth Maru CV.pdf
CONTACT
September 2025 -
December 2025
June 2024 -
September 2025
Aug 2024
May 2021
Parth Maru
Ahmedabad - 382350
9016509444
parthmaru1559@gmail.com
I am an SEO Executive with 1.5 year of experience, equipped with strong expertise in
keyword research, on-page, off- page, and technical SEO. I continuously stay updated
with the latest SEO trends to deliver measurable results and enhance website
performance.
SEO Executive
GEMS DIGITAL MEDIA
Handled 3–4 projects focusing on On-Page, Off-Page, and
==================================================
Processing: A_Priya.pdf
Page 1 of 3

Priya A
 +91 9344481662
 github.com/Priya2523

Ahmedabad, Gujarat

 Priya.AIDS25@aidtm.ac.in

linkedin.com/priya
Career Objective
Technology professional transitioning into AI & Data Science with experience in cloud platforms and
large-scale application environments. Interested in developing intelligent, data-driven systems that
combine analytical thinking with practical engineering execution.
Work Experience
Professional Experience | 2011 – 2024
Experience across e
==================================================
Processing: DHAIRYAKANT R HARSORA Resume-2.pdf
P R O J E C T S :
S U M M A R Y :
E D U C A T I O N :
C E R T I F I C A T I O N S :
DHAIRYAKANT HARSORA
Cyber Security & Networking Student
 Machine Learning Enthusiast | UI/UX Designer
+91 786-383-1521
Gandhidham, Kutch, Gujarat,
India 370201
dhairyakanth1924@gmail.com
C O N T A C T :
Tech Stack: Python, Scapy, Scikit-learn, Tkinter, Pandas, Matplotlib
Tech Stack: Java, Android Studio, Firebase, Firestore
Roles & Responsibilities:
Roles & Responsibilities:
INTRUSION DETECTION SYSTEM (IDS) USING
==================================================
Processing: MANSI GURAV Resumepdf.pdf
C o m p u t e r S c i e n c e E n g i n e e r i n g
s t u d e n t
M A N S I G U R A V
E D U C A T I O N
M.S. Gosavi polytechnic
institute Nashik
2020-2023
S K I L L S
Full Stack Development
(ASP.NET)
HTML, CSS, JAVASCRIPT,React
Python
UI/UX Design (Figma)
Graphic Designing (Basic)
Canva
Android Development (Basic)
Flutter (Basic)
P R O J E C T S
Dyslexia Screening System using Fuzzy Logic |Python,
Tkinter, Scikit-Fuzzy
ROLES & RESPONSIBILITIES:
P R O F I L E
Computer Science Engineering student

# Load the AI Embedding Model

In [20]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

# Compare Resume with All JDs

In [21]:
results = []

resume_embedding = model.encode(resume_text)

for jd_name, jd_text in jd_data.items():

    jd_embedding = model.encode(jd_text)

    score = cosine_similarity(
        [resume_embedding],
        [jd_embedding]
    )[0][0]

    results.append((jd_name, score))

# Sort by Match Score

In [22]:
results = sorted(results, key=lambda x: x[1], reverse=True)

for jd, score in results:
    print(f"{jd} --> {score*100:.2f}%")

BIM_MEP_Modeller.txt --> 54.75%
Transport_Executive.txt --> 35.80%
cyber_security_Intern.txt --> 27.39%
SEO_Executive.txt --> 22.32%
Full_Stack_Developer_Intern.txt --> 22.07%

# Find Matching Skills

In [23]:
jd_skills = {
    "BIM_MEP_Modeller.txt": [
        "Revit MEP",
        "AutoCAD",
        "Navisworks",
        "HVAC",
        "Plumbing",
        "Fire Fighting",
        "Clash Detection"
    ],

    "Transport_Executive.txt": [
        "Transportation Management",
        "Logistics",
        "Import Export",
        "SAP",
        "Fleet Management",
        "Dispatch",
        "Vendor Management"
    ],

    "cyber_security_Intern.txt": [
        "Python",
        "Networking",
        "Cyber Security",
        "IDS",
        "Machine Learning"
    ],

    "SEO_Executive.txt": [
        "SEO",
        "Google Analytics",
        "Keyword Research",
        "Technical SEO"
    ],

    "Full_Stack_Developer_Intern.txt": [
        "Python",
        "React",
        "HTML",
        "CSS",
        "JavaScript",
        "MySQL",
        "ASP.NET"
    ]
}

In [24]:
resume_lower = resume_text.lower()

for jd, skills in jd_skills.items():

    matched = []

    for skill in skills:
        if skill.lower() in resume_lower:
            matched.append(skill)

    print("\n", jd)
    print("Matched Skills:", matched)

 BIM_MEP_Modeller.txt
Matched Skills: ['Revit MEP', 'AutoCAD', 'HVAC', 'Plumbing', 'Fire Fighting', 'Clash Detection']

 Transport_Executive.txt
Matched Skills: []

 cyber_security_Intern.txt
Matched Skills: []

 SEO_Executive.txt
Matched Skills: []

 Full_Stack_Developer_Intern.txt
Matched Skills: []

In [25]:
best_jd, best_score = results[0]

print("Best Job Recommendation")
print("-----------------------")
print("Role :", best_jd)
print("Match :", round(best_score*100,2), "%")

Best Job Recommendation
-----------------------
Role : BIM_MEP_Modeller.txt
Match : 54.75 %

# Show Missing Skills

In [26]:
for jd, skills in jd_skills.items():

    matched = []
    missing = []

    for skill in skills:
        if skill.lower() in resume_text.lower():
            matched.append(skill)
        else:
            missing.append(skill)

    print("="*60)
    print("Job:", jd)
    print("Matched Skills :", matched)
    print("Missing Skills :", missing)

============================================================
Job: BIM_MEP_Modeller.txt
Matched Skills : ['Revit MEP', 'AutoCAD', 'HVAC', 'Plumbing', 'Fire Fighting', 'Clash Detection']
Missing Skills : ['Navisworks']
============================================================
Job: Transport_Executive.txt
Matched Skills : []
Missing Skills : ['Transportation Management', 'Logistics', 'Import Export', 'SAP', 'Fleet Management', 'Dispatch', 'Vendor Management']
============================================================
Job: cyber_security_Intern.txt
Matched Skills : []
Missing Skills : ['Python', 'Networking', 'Cyber Security', 'IDS', 'Machine Learning']
============================================================
Job: SEO_Executive.txt
Matched Skills : []
Missing Skills : ['SEO', 'Google Analytics', 'Keyword Research', 'Technical SEO']
============================================================
Job: Full_Stack_Developer_Intern.txt
Matched Skills : []
Missing Skills : ['Python', 'React', 'HTML', 'CSS', 'JavaScript', 'MySQL', 'ASP.NET']

# Generate Recruiter Feedback

In [27]:
best_jd, best_score = results[0]

matched = []
missing = []

for skill in jd_skills[best_jd]:
    if skill.lower() in resume_text.lower():
        matched.append(skill)
    else:
        missing.append(skill)

print("========== RecruitAI Recommendation ==========\n")

print("Recommended Role :", best_jd)
print("Match Score      :", round(best_score*100,2), "%")

print("\nMatched Skills")
for s in matched:
    print("✔", s)

print("\nMissing Skills")
for s in missing:
    print("✘", s)

========== RecruitAI Recommendation ==========

Recommended Role : BIM_MEP_Modeller.txt
Match Score      : 54.75 %

Matched Skills
✔ Revit MEP
✔ AutoCAD
✔ HVAC
✔ Plumbing
✔ Fire Fighting
✔ Clash Detection

Missing Skills
✘ Navisworks

# Correcting the workflow - load all resumes

In [28]:
import os

resume_folder = "Resume"

resume_files = [f for f in os.listdir() if f.endswith(".pdf")]
print(resume_files)

['Raja_Kullai_Resume.pdf', 'Parth Maru CV.pdf', 'A_Priya.pdf', 'DHAIRYAKANT R HARSORA Resume-2.pdf', 'MANSI GURAV Resumepdf.pdf']

# Read every resume

In [29]:
import os

resume_files = [f for f in os.listdir() if f.lower().endswith(".pdf")]
print(resume_files)

['Raja_Kullai_Resume.pdf', 'Parth Maru CV.pdf', 'A_Priya.pdf', 'DHAIRYAKANT R HARSORA Resume-2.pdf', 'MANSI GURAV Resumepdf.pdf']

In [30]:
all_resumes = {}

for file in resume_files:

    doc = fitz.open(file)

    text = ""

    for page in doc:
        text += page.get_text()

    doc.close()

    all_resumes[file] = text
print("Loaded",len(all_resumes),"resumes")

Loaded 5 resumes

In [31]:
selected_jd = "Transport_Executive.txt"

jd_text = jd_data[selected_jd]
jd_embedding = model.encode(jd_text)

# Compare all resumes

In [32]:
results = []

for resume_name, resume_text in all_resumes.items():

    resume_embedding = model.encode(resume_text)

    score = cosine_similarity(
        [jd_embedding],
        [resume_embedding]
    )[0][0]

    results.append((resume_name, score))

In [33]:
results = sorted(results, key=lambda x: x[1], reverse=True)

print("===== Candidate Ranking =====\n")

for i, (resume, score) in enumerate(results, start=1):
    print(f"{i}. {resume} --> {score*100:.2f}%")

===== Candidate Ranking =====

1. A_Priya.pdf --> 40.80%
2. Raja_Kullai_Resume.pdf --> 35.80%
3. Parth Maru CV.pdf --> 31.89%
4. MANSI GURAV Resumepdf.pdf --> 28.78%
5. DHAIRYAKANT R HARSORA Resume-2.pdf --> 21.34%

# matched skills

In [34]:
jd_skills = {
    "Transport_Executive.txt": [
        "Transportation Management",
        "Logistics",
        "Import",
        "Export",
        "Fleet Management",
        "SAP",
        "Dispatch",
        "Vendor Management"
    ]
}

In [35]:
selected_skills = jd_skills[selected_jd]

for resume_name, resume_text in all_resumes.items():

    matched = []

    for skill in selected_skills:
        if skill.lower() in resume_text.lower():
            matched.append(skill)

    print("="*60)
    print("Candidate :", resume_name)
    print("Matched Skills :", matched)

============================================================
Candidate : Raja_Kullai_Resume.pdf
Matched Skills : []
============================================================
Candidate : Parth Maru CV.pdf
Matched Skills : []
============================================================
Candidate : A_Priya.pdf
Matched Skills : []
============================================================
Candidate : DHAIRYAKANT R HARSORA Resume-2.pdf
Matched Skills : []
============================================================
Candidate : MANSI GURAV Resumepdf.pdf
Matched Skills : []

In [36]:
for resume_name, score in results:

    if score >= 0.75:
        decision = "✅ Strongly Recommended"

    elif score >= 0.60:
        decision = "🟡 Recommended"

    elif score >= 0.40:
        decision = "🟠 Consider"

    else:
        decision = "❌ Not Suitable"

    print(f"{resume_name:35} {score*100:.2f}%   {decision}")

A_Priya.pdf                         40.80%   🟠 Consider
Raja_Kullai_Resume.pdf              35.80%   ❌ Not Suitable
Parth Maru CV.pdf                   31.89%   ❌ Not Suitable
MANSI GURAV Resumepdf.pdf           28.78%   ❌ Not Suitable
DHAIRYAKANT R HARSORA Resume-2.pdf  21.34%   ❌ Not Suitable

RecruitAI Assistant

Upload JD

↓

Upload Resume Folder

↓

Upload Candidate Excel

↓

AI merges information

↓

Candidate Ranking

In [37]:
import re

In [38]:
def extract_skills(text, skill_list):
    text = text.lower()

    matched = []

    for skill in skill_list:
        if skill.lower() in text:
            matched.append(skill)

    return matched

In [39]:
MASTER_SKILLS = [

    "Python",
    "SQL",
    "Power BI",
    "Excel",
    "Tableau",

    "AWS",
    "Azure",
    "Docker",
    "Kubernetes",

    "Java",
    "C++",
    "React",
    "Node.js",

    "Machine Learning",
    "Deep Learning",
    "TensorFlow",
    "PyTorch",

    "Pandas",
    "NumPy",

    "SAP",
    "Logistics",
    "Fleet Management",
    "Import Export",

    "AutoCAD",
    "Revit MEP",
    "HVAC",
    "Fire Fighting"
]

In [40]:
candidate_profiles = []

for name, text in all_resumes.items():

    profile = {

        "Candidate": name,

        "Skills": extract_skills(text, MASTER_SKILLS),

        "Text": text

    }

    candidate_profiles.append(profile)

In [41]:
for candidate in candidate_profiles:

    print(candidate["Candidate"])

    print(candidate["Skills"])

    print("="*60)

Raja_Kullai_Resume.pdf
['Excel', 'AutoCAD', 'Revit MEP', 'HVAC', 'Fire Fighting']
============================================================
Parth Maru CV.pdf
[]
============================================================
A_Priya.pdf
['Python', 'SQL', 'Excel', 'AWS', 'Machine Learning', 'Pandas']
============================================================
DHAIRYAKANT R HARSORA Resume-2.pdf
['Python', 'Java', 'Machine Learning', 'Pandas']
============================================================
MANSI GURAV Resumepdf.pdf
['Python', 'SQL', 'Java', 'React', 'Node.js']
============================================================

In [42]:
jd_profile = {}

jd_profile["Skills"] = extract_skills(jd_text, MASTER_SKILLS)

print(jd_profile)

{'Skills': ['Excel', 'SAP', 'Logistics']}

In [43]:
!pip install -q groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 9.4 MB/s eta 0:00:00

In [44]:
from groq import Groq
from google.colab import userdata

In [82]:
api_key = userdata.get("recruit_api")

client = Groq(api_key=api_key)

In [83]:
response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "user",
            "content": "Reply with only one word: Connected"
        }
    ],
    temperature=0
)

print(response.choices[0].message.content)

Linked

# Create the JD Parser

In [84]:
import json
import re

def parse_jd_with_groq(jd_text):

    prompt = f"""
You are an expert recruitment assistant.

Extract the following information from this Job Description.

Return ONLY valid JSON.

Format:

{{
    "job_title":"",
    "skills":[],
    "experience":"",
    "education":"",
    "location":""
}}

Job Description:

{jd_text}
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        temperature=0,
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ]
    )

    result = response.choices[0].message.content.strip()

    # Remove markdown code blocks if present
    result = re.sub(r"^```json", "", result)
    result = re.sub(r"^```", "", result)
    result = re.sub(r"```$", "", result)
    result = result.strip()

    return json.loads(result)

In [85]:
jd_profile = parse_jd_with_groq(jd_text)

print(jd_profile)

{'job_title': 'Transport Executive', 'skills': ['Transportation Management', 'Logistics Coordination', 'Import & Export Documentation', 'Customs Clearance', 'Shipment Tracking', 'Freight Coordination', 'Vendor Management', 'Microsoft Excel', 'ERP Systems (SAP / Oracle)', 'Communication Skills', 'Negotiation Skills', 'Documentation Management'], 'experience': '2-5 Years', 'education': "Bachelor's Degree in Logistics, Supply Chain Management, Commerce, Business Administration, or a related field.", 'location': 'Mumbai'}

# build the Resume Parser

In [86]:
import json
import re

def parse_resume_with_groq(resume_text):

    prompt = f"""
You are an expert recruitment assistant.

Extract information from this resume.

Return ONLY valid JSON.

Format:

{{
    "candidate_name":"",
    "skills":[],
    "experience":"",
    "education":"",
    "location":"",
    "certifications":[],
    "projects":[]
}}

Resume:

{resume_text}
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        temperature=0,
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ]
    )

    result = response.choices[0].message.content.strip()

    result = re.sub(r"^```json", "", result)
    result = re.sub(r"^```", "", result)
    result = re.sub(r"```$", "", result)

    result = result.strip()

    return json.loads(result)

In [50]:
resume_profile = parse_resume_with_groq(
    all_resumes["A_Priya.pdf"]
)

print(json.dumps(resume_profile, indent=4))

{
    "candidate_name": "Priya A",
    "skills": [
        "Cloud",
        "Programming",
        "AI",
        "EC2",
        "SQL",
        "LLM",
        "Python",
        "Lang Chain",
        "S3",
        "Agentic Al",
        "CloudFormation",
        "Hugging Face"
    ],
    "experience": "12+ years",
    "education": "PGDM in AI & DS from Adani Institute of Digital Technology Management, B. Tech IT from Lingaya\u2019s Vidyapeeth",
    "location": "Ahmedabad, Gujarat",
    "certifications": [
        "Python 101 for Data Science By IBM",
        "SQL and Relational Databases 101 By IBM",
        "AWS Certified DevOps Engineer \u2013 Professional"
    ],
    "projects": [
        "Real Estate Value Predictor - Agentic AI System",
        "Parking Occupancy Detection System",
        "Secure Cloud Networking (AWS)",
        "Hotel Ratings & Tariff Analysis",
        "Fashion Recommendation System"
    ]
}

# Create a Recruiter Evaluator

In [51]:
import json
import re

def evaluate_candidate(jd_profile, resume_profile):

    prompt = f"""
You are an experienced technical recruiter.

Evaluate the candidate against the Job Description.

Job Description:

{json.dumps(jd_profile, indent=2)}

Candidate:

{json.dumps(resume_profile, indent=2)}

Return ONLY valid JSON.

Format:

{{
  "overall_score": 0,
  "matched_skills": [],
  "missing_skills": [],
  "strengths": [],
  "concerns": [],
  "recommendation": ""
}}

Scoring should be fair and based on:
- Skills
- Experience
- Education
- Location
- Certifications
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        temperature=0,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    result = response.choices[0].message.content.strip()

    result = re.sub(r"^```json", "", result)
    result = re.sub(r"^```", "", result)
    result = re.sub(r"```$", "", result)
    result = result.strip()

    return json.loads(result)

In [52]:
evaluation = evaluate_candidate(jd_profile, resume_profile)

print(json.dumps(evaluation, indent=4))

{
    "overall_score": 0,
    "matched_skills": [],
    "missing_skills": [
        "Transportation Management",
        "Logistics Coordination",
        "Import & Export Documentation",
        "Customs Clearance",
        "Shipment Tracking",
        "Freight Coordination",
        "Vendor Management",
        "Microsoft Excel",
        "ERP Systems (SAP / Oracle)",
        "Communication Skills",
        "Negotiation Skills",
        "Documentation Management"
    ],
    "strengths": [
        "Strong technical background",
        "Experience with cloud-based technologies",
        "Certifications in AWS and programming languages"
    ],
    "concerns": [
        "Lack of relevant skills for the Transport Executive role",
        "No experience in logistics or transportation management",
        "Location is not a match (Ahmedabad instead of Mumbai)",
        "Overqualified in terms of experience (12+ years vs 2-5 years)"
    ],
    "recommendation": "Not a good fit for the Transport Executive role due to lack of relevant skills and experience. May be considered for other technical roles within the company."
}

In [53]:
import json
import re

def evaluate_candidate(jd_profile, resume_profile):

    prompt = f"""
You are an experienced recruiter.

Compare the Job Description with the Candidate profile.

Scoring Rules:

Skills = 40 points
Experience = 20 points
Education = 10 points
Location = 10 points
Certifications = 10 points
Communication & Overall Profile = 10 points

The total overall_score MUST be between 0 and 100.

Job Description:

{json.dumps(jd_profile, indent=2)}

Candidate:

{json.dumps(resume_profile, indent=2)}

Return ONLY valid JSON.

{{
    "overall_score": 0,
    "skill_score": 0,
    "experience_score": 0,
    "education_score": 0,
    "location_score": 0,
    "certification_score": 0,
    "communication_score": 0,
    "matched_skills": [],
    "missing_skills": [],
    "strengths": [],
    "concerns": [],
    "recommendation": ""
}}
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        temperature=0,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    result = response.choices[0].message.content.strip()

    result = re.sub(r"^```json", "", result)
    result = re.sub(r"^```", "", result)
    result = re.sub(r"```$", "", result)
    result = result.strip()

    return json.loads(result)

In [54]:
evaluation = evaluate_candidate(jd_profile, resume_profile)

print(json.dumps(evaluation, indent=4))

{
    "overall_score": 6,
    "skill_score": 0,
    "experience_score": 0,
    "education_score": 5,
    "location_score": 0,
    "certification_score": 1,
    "communication_score": 0,
    "matched_skills": [],
    "missing_skills": [
        "Transportation Management",
        "Logistics Coordination",
        "Import & Export Documentation",
        "Customs Clearance",
        "Shipment Tracking",
        "Freight Coordination",
        "Vendor Management",
        "Microsoft Excel",
        "ERP Systems (SAP / Oracle)",
        "Communication Skills",
        "Negotiation Skills",
        "Documentation Management"
    ],
    "strengths": [
        "Strong technical background",
        "Multiple certifications",
        "Experience in projects"
    ],
    "concerns": [
        "No relevant skills for the job",
        "Location mismatch",
        "Overqualified for the experience required"
    ],
    "recommendation": "Not recommended for the Transport Executive role due to lack of relevant skills and location mismatch."
}

In [55]:
all_candidate_profiles = []

for filename, resume_text in all_resumes.items():

    print(f"Parsing {filename}...")

    profile = parse_resume_with_groq(resume_text)

    profile["file_name"] = filename

    all_candidate_profiles.append(profile)

print("Done!")

Parsing Raja_Kullai_Resume.pdf...
Parsing Parth Maru CV.pdf...
Parsing A_Priya.pdf...
Parsing DHAIRYAKANT R HARSORA Resume-2.pdf...
Parsing MANSI GURAV Resumepdf.pdf...
Done!

In [56]:
for profile in all_candidate_profiles:

    print("="*60)

    print(profile["candidate_name"])

    print(profile["skills"])

    print(profile["experience"])

============================================================
D.Raja Kullai
['Autodesk Revit MEP', 'Autodesk Autocad', 'Autodesk NavisWork', 'Autodesk ReCap', 'MS Office', '3D Modelling', 'Designing', 'Clash detection', 'Pointcloud']
3 years
============================================================
Parth Maru
['AEO', 'On-Page SEO', 'Off-Page SEO', 'Technical SEO', 'SEO Tools Knowledge', 'Reporting & Analysis']
1.5 years
============================================================
Priya A
['Cloud', 'Programming', 'AI', 'EC2', 'SQL', 'LLM', 'Python', 'Lang Chain', 'S3', 'Agentic Al', 'CloudFormation', 'Hugging Face']
2011-2024 (Professional Experience), Dec 2025 - Jan 2026 (Internship Experience), March 2026 - Present (Recruitment Internship)
============================================================
DHAIRYAKANT HARSORA
['Python', 'Java', 'Machine Learning', 'OpenCV', 'Firebase', 'Ethical Hacking and Cybersecurity', 'Network Monitoring', 'UI/UX', 'Static & Dynamic Web Design', 'Canva', 'Android Development', 'Intrusion Detection Systems (IDS)']

============================================================
Mansi Gurav
['Full Stack Development', 'ASP.NET', 'HTML', 'CSS', 'JAVASCRIPT', 'React', 'Python', 'UI/UX Design', 'Figma', 'Graphic Designing', 'Canva', 'Android Development', 'Flutter', 'Java', 'Firebase']

# Evaluate every resume against the JD

In [57]:
all_evaluations = []

for candidate in all_candidate_profiles:

    print(f"Evaluating {candidate['candidate_name']}...")

    evaluation = evaluate_candidate(jd_profile, candidate)

    evaluation["candidate_name"] = candidate["candidate_name"]
    evaluation["file_name"] = candidate["file_name"]

    all_evaluations.append(evaluation)

print("Evaluation completed!")

Evaluating D.Raja Kullai...
Evaluating Parth Maru...
Evaluating Priya A...
Evaluating DHAIRYAKANT HARSORA...
Evaluating Mansi Gurav...
Evaluation completed!

# Display the results

In [58]:
for result in all_evaluations:

    print("="*80)
    print("Candidate :", result["candidate_name"])
    print("Score :", result["overall_score"])
    print("Recommendation :", result["recommendation"])

================================================================================
Candidate : D.Raja Kullai
Score : 8
Recommendation : Not a strong fit for the Transport Executive role due to lack of relevant skills and education. May require significant training or upskilling.
================================================================================
Candidate : Parth Maru
Score : 6
Recommendation : Not recommended for the Transport Executive role due to lack of relevant skills and experience.
================================================================================
Candidate : Priya A
Score : 10
Recommendation : Not recommended for the Transport Executive role due to lack of relevant skills and experience. However, the candidate's technical skills could be valuable in other roles.
================================================================================
Candidate : DHAIRYAKANT HARSORA
Score : 6
Recommendation : The candidate does not seem to be a good fit for the Transport Executive role due to the lack of relevant skills and experience. However, they have strong technical skills that could be valuable in other roles.
================================================================================
Candidate : Mansi Gurav
Score : 10
Recommendation : The candidate does not seem to be a good fit for the Transport Executive role due to the lack of relevant skills and experience. However, they have strong technical skills that could be valuable in other roles.

# Create a recruiter dashboard

In [59]:
import pandas as pd

summary = []

for result in all_evaluations:

    summary.append({
        "Candidate": result["candidate_name"],
        "Score": result["overall_score"],
        "Recommendation": result["recommendation"]
    })

df = pd.DataFrame(summary)

df = df.sort_values(by="Score", ascending=False)

df

,Candidate,Score,Recommendation
2,Priya A,10,Not recommended for the Transport Executive ro...
4,Mansi Gurav,10,The candidate does not seem to be a good fit f...
0,D.Raja Kullai,8,Not a strong fit for the Transport Executive r...
1,Parth Maru,6,Not recommended for the Transport Executive ro...
3,DHAIRYAKANT HARSORA,6,The candidate does not seem to be a good fit f...

In [60]:
import pandas as pd

summary = []

for result in all_evaluations:

    summary = []

for result in all_evaluations:

    summary.append({
        "Candidate": result["candidate_name"],
        "Score": result["overall_score"],
        "Recommendation": result["recommendation"],
        "Strengths": ", ".join(result["strengths"]),
        "Concerns": ", ".join(result["concerns"]),
        "Matched Skills": ", ".join(result["matched_skills"]),
        "Missing Skills": ", ".join(result["missing_skills"])
    })

df = pd.DataFrame(summary)

df = df.sort_values(by="Score", ascending=False)

df

,Candidate,Score,Recommendation,Strengths,Concerns,Matched Skills,Missing Skills
2,Priya A,10,Not recommended for the Transport Executive ro...,"Strong technical skills, Experience with cloud...",Lack of relevant skills for the Transport Exec...,,"Transportation Management, Logistics Coordinat..."
4,Mansi Gurav,10,The candidate does not seem to be a good fit f...,"Technical skills in Full Stack Development, Ex...",Lack of relevant skills and experience for the...,,"Transportation Management, Logistics Coordinat..."
0,D.Raja Kullai,8,Not a strong fit for the Transport Executive r...,"Relevant work experience of 3 years, Location ...","No relevant skills for the job, Education does...",,"Transportation Management, Logistics Coordinat..."
1,Parth Maru,6,Not recommended for the Transport Executive ro...,,"Lack of relevant skills, Insufficient experien...",,"Transportation Management, Logistics Coordinat..."
3,DHAIRYAKANT HARSORA,6,The candidate does not seem to be a good fit f...,"Strong technical skills in areas like Python, ...",Lack of relevant skills for the Transport Exec...,,"Transportation Management, Logistics Coordinat..."

In [61]:
import json
import re

def evaluate_candidate(jd_profile, resume_profile):

    prompt = f"""
You are an experienced Senior HR Recruitment Manager.

Your task is to compare a Job Description with a Candidate Profile.

Think like a recruiter.

Do NOT simply compare keywords.

Analyze:

1. Technical Skills
2. Domain Experience
3. Education
4. Certifications
5. Location
6. Overall suitability

If the candidate is NOT suitable,
suggest 3 better job roles based on the candidate profile.

Finally decide ONE of these:

- Strong Fit
- Good Fit
- Partial Fit
- Not Fit

Interview Decision must be ONLY one:

- Shortlist
- Hold
- Reject

Job Description

{json.dumps(jd_profile, indent=2)}

Candidate Profile

{json.dumps(resume_profile, indent=2)}

Return ONLY valid JSON.

{{
    "overall_score": 0,
    "fit_level": "",
    "reasoning": [],
    "better_suited_roles": [],
    "interview_decision": "",
    "matched_skills": [],
    "missing_skills": [],
    "strengths": [],
    "concerns": [],
    "recommendation": ""
}}
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    result = response.choices[0].message.content.strip()

    result = re.sub(r"^```json", "", result)
    result = re.sub(r"^```", "", result)
    result = re.sub(r"```$", "", result)
    result = result.strip()

    return json.loads(result)

In [62]:
all_evaluations = []

for candidate in all_candidate_profiles:

    print(f"Evaluating {candidate['candidate_name']}...")

    evaluation = evaluate_candidate(jd_profile, candidate)

    evaluation["candidate_name"] = candidate["candidate_name"]
    evaluation["file_name"] = candidate["file_name"]

    all_evaluations.append(evaluation)

print("Evaluation completed!")

Evaluating D.Raja Kullai...
Evaluating Parth Maru...
Evaluating Priya A...
Evaluating DHAIRYAKANT HARSORA...
Evaluating Mansi Gurav...
Evaluation completed!

In [63]:
import pandas as pd

summary = []

for result in all_evaluations:

    summary.append({

        "Candidate": result["candidate_name"],

        "Score": result["overall_score"],

        "Fit Level": result["fit_level"],

        "Interview": result["interview_decision"],

        "Better Roles": ", ".join(result["better_suited_roles"]),

        "Recommendation": result["recommendation"]

    })

df = pd.DataFrame(summary)

df = df.sort_values(by="Score", ascending=False)

df

,Candidate,Score,Fit Level,Interview,Better Roles,Recommendation
0,D.Raja Kullai,0,Not Fit,Reject,"Design Engineer, MEP Coordinator, BIM Specialist",The candidate's skills and experience are not ...
1,Parth Maru,0,Not Fit,Reject,"Digital Marketing Executive, SEO Specialist, D...",The candidate should consider roles that align...
2,Priya A,0,Not Fit,Reject,"Cloud Engineer, Data Scientist, AI/ML Engineer",The candidate's skills and experience are not ...
3,DHAIRYAKANT HARSORA,0,Not Fit,Reject,"Cybersecurity Specialist, Software Developer, ...",The candidate should consider developing skill...
4,Mansi Gurav,0,Not Fit,Reject,"Junior Software Developer, UI/UX Designer, Ful...",The candidate should consider roles that align...

In [64]:
for result in all_evaluations:

    print("=" * 100)

    print("Candidate:", result["candidate_name"])

    print("Score:", result["overall_score"])

    print("Fit Level:", result["fit_level"])

    print("Interview Decision:", result["interview_decision"])

    print("\nBetter Roles:")
    for role in result["better_suited_roles"]:
        print("-", role)

    print("\nReasoning:")
    for reason in result["reasoning"]:
        print("-", reason)

    print("\nStrengths:")
    for strength in result["strengths"]:
        print("-", strength)

    print("\nConcerns:")
    for concern in result["concerns"]:
        print("-", concern)

    print("\nRecommendation:")
    print(result["recommendation"])

    print("\n")

====================================================================================================
Candidate: D.Raja Kullai
Score: 0
Fit Level: Not Fit
Interview Decision: Reject

Better Roles:
- Design Engineer
- MEP Coordinator
- BIM Specialist

Reasoning:
- The candidate's technical skills are primarily focused on Autodesk software and 3D modeling, which do not align with the job requirements of a Transport Executive.
- The candidate's domain experience is in mechanical engineering and design, whereas the job requires experience in transportation management and logistics.
- The candidate's education is in mechanical engineering, which is not directly related to the preferred education for the job.
- The candidate lacks certifications and relevant skills such as Import & Export Documentation, Customs Clearance, and ERP Systems.

Strengths:
- Proficient in Autodesk software
- Experience in 3D modeling and design

Concerns:
- Lack of relevant experience in transportation management and logistics
- Limited skills in documentation management and communication

Recommendation:
The candidate's skills and experience are not aligned with the job requirements of a Transport Executive. However, they may be a good fit for roles that utilize their technical skills in design and engineering.


====================================================================================================
Candidate: Parth Maru
Score: 0
Fit Level: Not Fit
Interview Decision: Reject

Better Roles:
- Digital Marketing Executive
- SEO Specialist
- Data Analyst

Reasoning:
- The candidate's technical skills do not match the job requirements, with no experience in transportation management, logistics coordination, or related fields.
- The candidate's domain experience is in SEO and digital media, which is unrelated to the transport executive role.
- The candidate's education is in computer applications, which does not meet the job's educational requirements.
- The candidate's location is Ahmedabad, which does not match the job's location in Mumbai.

Strengths:
- Experience in SEO and digital media
- Skills in reporting and analysis

Concerns:
- Lack of relevant technical skills
- No experience in transportation or logistics
- Location mismatch

Recommendation:
The candidate should consider roles that align with their skills and experience in digital marketing and SEO.


====================================================================================================
Candidate: Priya A
Score: 0
Fit Level: Not Fit
Interview Decision: Reject

Better Roles:
- Cloud Engineer
- Data Scientist
- AI/ML Engineer

Reasoning:
- The candidate's technical skills are primarily focused on cloud computing, programming, and AI, which do not align with the job requirements of a Transport Executive.
- The candidate lacks experience in transportation management, logistics coordination, and customs clearance, which are essential skills for the role.
- The candidate's education background is in AI and digital technology management, which is not directly related to the field of logistics or supply chain management.
- The candidate's location is Ahmedabad, Gujarat, whereas the job is based in Mumbai.

Strengths:
- Strong technical skills in cloud computing and programming
- Experience with AI and machine learning
- Certifications in AWS and Python

Concerns:
- Lack of experience in logistics and supply chain management
- Limited knowledge of transportation management and customs clearance
- Location mismatch

Recommendation:
The candidate's skills and experience are not aligned with the requirements of the Transport Executive role. However, they may be a strong fit for roles that utilize their technical skills in cloud computing, programming, and AI.


====================================================================================================
Candidate: DHAIRYAKANT HARSORA
Score: 0
Fit Level: Not Fit
Interview Decision: Reject

Better Roles:
- Cybersecurity Specialist
- Software Developer
- Network Administrator

Reasoning:
- The candidate's technical skills are primarily focused on programming, cybersecurity, and web development, which do not align with the job requirements for a Transport Executive.
- The candidate lacks domain experience in transportation management, logistics coordination, and related fields.
- The candidate's education background is in Cyber Security & Networking, which is not directly related to the preferred education for the job.
- The candidate's location is in Gandhidham, Gujarat, whereas the job is based in Mumbai.

Strengths:
- Proficiency in programming languages such as Python and Java
- Experience in machine learning and cybersecurity
- Participation in designathons and development of personal projects

Concerns:
- Lack of relevant experience in the transportation and logistics industry
- Limited skills in Microsoft Excel and ERP systems
- No experience in vendor management and negotiation

Recommendation:
The candidate should consider developing skills in transportation management, logistics coordination, and related fields to increase their chances of being considered for the Transport Executive role.


====================================================================================================
Candidate: Mansi Gurav
Score: 0
Fit Level: Not Fit
Interview Decision: Reject

Better Roles:
- Junior Software Developer
- UI/UX Designer
- Full Stack Developer

Reasoning:
- The candidate's technical skills are primarily focused on full stack development, UI/UX design, and programming, which do not align with the job requirements of a Transport Executive.
- The candidate lacks domain experience in transportation management, logistics coordination, and customs clearance.
- The candidate's education background is in computer science engineering, which does not match the preferred education for the job.
- The candidate's location is Nashik, which is not the preferred location for the job.

Strengths:
- Proficient in full stack development
- Experience with UI/UX design tools
- Strong programming skills

Concerns:
- Lack of domain experience in transportation management
- No relevant certifications or training in logistics or supply chain management
- Location is not preferred for the job

Recommendation:
The candidate should consider roles that align with their technical skills and education background, such as software development or UI/UX design.

# Python Scoring Engine

In [65]:
print(json.dumps(all_candidate_profiles[0], indent=4))

{
    "candidate_name": "D.Raja Kullai",
    "skills": [
        "Autodesk Revit MEP",
        "Autodesk Autocad",
        "Autodesk NavisWork",
        "Autodesk ReCap",
        "MS Office",
        "3D Modelling",
        "Designing",
        "Clash detection",
        "Pointcloud"
    ],
    "experience": "3 years",
    "education": "Bachelor of Technology in Mechanical Engineering, Diploma in Mechanical Engineering",
    "location": "India",
    "certifications": [],
    "projects": [
        "Yashoda Hospital Expansion \u2013 Hospital Project",
        "Kempegowda International Airport \u2013 T2 MEP Modelling Project"
    ],
    "file_name": "Raja_Kullai_Resume.pdf"
}

In [66]:
print(json.dumps(jd_profile, indent=4))

{
    "job_title": "Transport Executive",
    "skills": [
        "Transportation Management",
        "Logistics Coordination",
        "Import & Export Documentation",
        "Customs Clearance",
        "Shipment Tracking",
        "Freight Coordination",
        "Vendor Management",
        "Microsoft Excel",
        "ERP Systems (SAP / Oracle)",
        "Communication Skills",
        "Negotiation Skills",
        "Documentation Management"
    ],
    "experience": "2-5 Years",
    "education": "Bachelor's Degree in Logistics, Supply Chain Management, Commerce, Business Administration, or a related field.",
    "location": "Mumbai"
}

In [67]:
import re

def extract_years(exp_text):
    """
    Extract numeric years from strings like:
    '3 years'
    '13 Years'
    '2-5 Years'
    """
    numbers = re.findall(r"\d+", str(exp_text))

    if not numbers:
        return 0

    return int(numbers[0])


def calculate_score(jd_profile, resume_profile):

    score = 0

    breakdown = {}

    #########################################
    # Skills (40 Marks)
    #########################################

    jd_skills = set(skill.lower() for skill in jd_profile["skills"])
    resume_skills = set(skill.lower() for skill in resume_profile["skills"])

    matched = jd_skills.intersection(resume_skills)

    if len(jd_skills) > 0:
        skill_score = round((len(matched) / len(jd_skills)) * 40)
    else:
        skill_score = 0

    score += skill_score
    breakdown["Skill Score"] = skill_score

    #########################################
    # Experience (20 Marks)
    #########################################

    candidate_years = extract_years(resume_profile["experience"])

    jd_min = extract_years(jd_profile["experience"])

    if candidate_years >= jd_min:
        experience_score = 20
    else:
        experience_score = round((candidate_years / jd_min) * 20)

    score += experience_score
    breakdown["Experience Score"] = experience_score

    #########################################
    # Education (10 Marks)
    #########################################

    education = resume_profile["education"].lower()

    if "bachelor" in education or "b.tech" in education:
        education_score = 10
    elif "diploma" in education:
        education_score = 5
    else:
        education_score = 0

    score += education_score
    breakdown["Education Score"] = education_score

    #########################################
    # Location (10 Marks)
    #########################################

    if jd_profile["location"].lower() in resume_profile["location"].lower():
        location_score = 10
    else:
        location_score = 5

    score += location_score
    breakdown["Location Score"] = location_score

    #########################################
    # Certifications (10 Marks)
    #########################################

    if len(resume_profile["certifications"]) >= 3:
        cert_score = 10
    elif len(resume_profile["certifications"]) >= 1:
        cert_score = 5
    else:
        cert_score = 0

    score += cert_score
    breakdown["Certification Score"] = cert_score

    #########################################
    # Projects / Profile (10 Marks)
    #########################################

    if len(resume_profile["projects"]) >= 3:
        profile_score = 10
    elif len(resume_profile["projects"]) >= 1:
        profile_score = 5
    else:
        profile_score = 0

    score += profile_score
    breakdown["Profile Score"] = profile_score

    return score, breakdown

In [68]:
all_evaluations = []

for candidate in all_candidate_profiles:

    evaluation = evaluate_candidate(jd_profile, candidate)

    python_score, score_breakdown = calculate_score(
        jd_profile,
        candidate
    )

    evaluation["overall_score"] = python_score
    evaluation["score_breakdown"] = score_breakdown
    evaluation["candidate_name"] = candidate["candidate_name"]
    evaluation["file_name"] = candidate["file_name"]

    all_evaluations.append(evaluation)

print("Evaluation completed!")

Evaluation completed!

In [69]:
print(all_evaluations[0])

{'overall_score': 40, 'fit_level': 'Not Fit', 'reasoning': ["The candidate's technical skills are primarily focused on Autodesk software and 3D modeling, which do not align with the required skills for a Transport Executive role.", "The candidate's domain experience is in mechanical engineering and design, whereas the job requires experience in transportation management and logistics.", "The candidate's education is in mechanical engineering, which does not match the required education in logistics, supply chain management, or a related field.", "The candidate's location is only mentioned as India, which is not specific enough to confirm if they are based in Mumbai or willing to relocate."], 'better_suited_roles': ['Design Engineer', 'MEP Coordinator', 'BIM Specialist'], 'interview_decision': 'Reject', 'matched_skills': ['MS Office'], 'missing_skills': ['Transportation Management', 'Logistics Coordination', 'Import & Export Documentation', 'Customs Clearance', 'Shipment Tracking', 'Freight Coordination', 'Vendor Management', 'ERP Systems (SAP / Oracle)', 'Communication Skills', 'Negotiation Skills', 'Documentation Management'], 'strengths': ['Proficiency in Autodesk software', 'Experience in 3D modeling and design'], 'concerns': ['Lack of relevant experience in transportation management and logistics', 'Limited skills in Microsoft Excel and ERP systems', 'No certifications or training in logistics or supply chain management'], 'recommendation': "The candidate's skills and experience are not aligned with the requirements of the Transport Executive role. They may be better suited for roles that utilize their technical skills in design and engineering.", 'score_breakdown': {'Skill Score': 0, 'Experience Score': 20, 'Education Score': 10, 'Location Score': 5, 'Certification Score': 0, 'Profile Score': 5}, 'candidate_name': 'D.Raja Kullai', 'file_name': 'Raja_Kullai_Resume.pdf'}

In [70]:
import re

def extract_years(exp_text):
    numbers = re.findall(r"\d+", str(exp_text))
    if not numbers:
        return 0

    # Handle "2-5 Years" by taking the first number for minimum
    return int(numbers[0])


def calculate_score(jd_profile, resume_profile):

    score = 0
    breakdown = {}

    ####################################################
    # Skill Score (40)
    ####################################################

    skill_alias = {
        "microsoft excel": ["excel", "ms excel", "microsoft excel", "excell", "ms office"],
        "erp systems (sap / oracle)": ["sap", "oracle"],
        "communication skills": ["communication", "communication skills"],
        "documentation management": ["documentation"]
    }

    resume_skills = [s.lower() for s in resume_profile["skills"]]
    jd_skills = [s.lower() for s in jd_profile["skills"]]

    matched = 0

    for jd_skill in jd_skills:

        found = False

        if jd_skill in skill_alias:

            for alias in skill_alias[jd_skill]:
                if any(alias in rs for rs in resume_skills):
                    found = True
                    break

        else:

            if any(jd_skill in rs for rs in resume_skills):
                found = True

        if found:
            matched += 1

    skill_score = round((matched / len(jd_skills)) * 40)

    score += skill_score

    breakdown["Skill Score"] = skill_score

    ####################################################
    # Experience (20)
    ####################################################

    candidate_years = extract_years(resume_profile["experience"])

    exp = jd_profile["experience"]

    nums = re.findall(r"\d+", exp)

    jd_min = int(nums[0])
    jd_max = int(nums[1])

    if jd_min <= candidate_years <= jd_max:
        experience_score = 20

    elif candidate_years > jd_max:
        experience_score = 15

    elif candidate_years >= (jd_min - 1):
        experience_score = 10

    else:
        experience_score = 5

    score += experience_score

    breakdown["Experience Score"] = experience_score

    ####################################################
    # Education (10)
    ####################################################

    education = resume_profile["education"].lower()

    if any(x in education for x in ["logistics","supply chain","commerce","business administration"]):
        education_score = 10

    elif "bachelor" in education or "b.tech" in education:
        education_score = 7

    elif "diploma" in education:
        education_score = 5

    else:
        education_score = 2

    score += education_score

    breakdown["Education Score"] = education_score

    ####################################################
    # Location (10)
    ####################################################

    if jd_profile["location"].lower() in resume_profile["location"].lower():

        location_score = 10

    else:

        location_score = 5

    score += location_score

    breakdown["Location Score"] = location_score

    ####################################################
    # Certifications (10)
    ####################################################

    certs = len(resume_profile["certifications"])

    if certs >= 3:
        cert_score = 10

    elif certs >= 1:
        cert_score = 6

    else:
        cert_score = 2

    score += cert_score

    breakdown["Certification Score"] = cert_score

    ####################################################
    # Projects (10)
    ####################################################

    projects = len(resume_profile["projects"])

    if projects >= 3:
        project_score = 10

    elif projects >= 1:
        project_score = 7

    else:
        project_score = 2

    score += project_score

    breakdown["Project Score"] = project_score

    return score, breakdown

In [71]:
for r in all_evaluations:
    print(r["candidate_name"])
    print(r["overall_score"])
    print(r["score_breakdown"])
    print("-"*60)

D.Raja Kullai
40
{'Skill Score': 0, 'Experience Score': 20, 'Education Score': 10, 'Location Score': 5, 'Certification Score': 0, 'Profile Score': 5}
------------------------------------------------------------
Parth Maru
20
{'Skill Score': 0, 'Experience Score': 10, 'Education Score': 0, 'Location Score': 5, 'Certification Score': 0, 'Profile Score': 5}
------------------------------------------------------------
Priya A
45
{'Skill Score': 0, 'Experience Score': 20, 'Education Score': 0, 'Location Score': 5, 'Certification Score': 10, 'Profile Score': 10}
------------------------------------------------------------
DHAIRYAKANT HARSORA
25
{'Skill Score': 0, 'Experience Score': 0, 'Education Score': 10, 'Location Score': 5, 'Certification Score': 5, 'Profile Score': 5}
------------------------------------------------------------
Mansi Gurav
30
{'Skill Score': 0, 'Experience Score': 0, 'Education Score': 10, 'Location Score': 5, 'Certification Score': 10, 'Profile Score': 5}
------------------------------------------------------------

In [87]:
import gradio as gr
print(gr.__version__)

6.20.0

In [84]:
import pandas as pd

def evaluate_pipeline(jd_file, resume_files):

    print(type(resume_files))
    print(resume_files)

    if resume_files:
        print("Number of resumes:", len(resume_files))
        for r in resume_files:
            print(r.name)

def evaluate_pipeline(jd_file, resume_files):

    # ---------- Read JD ----------
    with open(jd_file.name, "r", encoding="utf-8") as f:
        jd_text = f.read()

    jd_profile = parse_jd_with_groq(jd_text)

    results = []

    # ---------- Read each resume ----------
    for resume in resume_files:

        text = extract_text_from_pdf(resume.name)

        profile = parse_resume_with_groq(text)

        python_score, breakdown = calculate_score(
            jd_profile,
            profile
        )

        ai_result = evaluate_candidate(
            jd_profile,
            profile
        )

        ai_result["overall_score"] = python_score

        results.append([
            profile["candidate_name"],
            python_score,
            ai_result["fit_level"],
            ai_result["interview_decision"]
        ])

    df = pd.DataFrame(
        results,
        columns=[
            "Candidate",
            "Score",
            "Fit Level",
            "Interview Decision"
        ]
    )

    df = df.sort_values(
        "Score",
        ascending=False
    )

    return df

In [86]:
import gradio as gr

with gr.Blocks(title="RecruitAI") as demo:

    gr.Markdown("# 🤖 RecruitAI - Intelligent Recruitment Assistant")
    gr.Markdown("Upload a Job Description and Resume Folder to evaluate candidates.")

    with gr.Row():
        jd_file = gr.File(label="📄 Upload Job Description")

        resume_files = gr.File(
            label="📁 Upload Resume Folder",
            file_count="multiple"
        )

    evaluate_btn = gr.Button("🚀 Evaluate Candidates")

    gr.Markdown("## 📊 Candidate Ranking")

    results_table = gr.Dataframe(
        headers=[
            "Candidate",
            "Score",
            "Fit Level",
            "Interview Decision"
        ],
        interactive=False
    )

    evaluate_btn.click(
        fn=evaluate_pipeline,
        inputs=[jd_file, resume_files],
        outputs=results_table
    )

demo.launch(debug=True)

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://741ddaad23674afe1b.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://741ddaad23674afe1b.gradio.live

In [87]:
import pandas as pd

def evaluate_pipeline(jd_file, resume_files):

    # Read JD
    with open(jd_file.name, "r", encoding="utf-8") as f:
        jd_text = f.read()

    jd_profile = parse_jd_with_groq(jd_text)

    required_skills = jd_profile.get("skills", [])

    results = []

    for resume in resume_files:

        try:

            resume_text = extract_text_from_pdf(resume.name)

            profile = parse_resume_with_groq(resume_text)

            python_score, breakdown = calculate_score(
                jd_profile,
                profile
            )

            ai_result = evaluate_candidate(
                jd_profile,
                profile
            )

            candidate_skills = profile.get("skills", [])

            matched_skills = [
                skill
                for skill in candidate_skills
                if skill.lower() in [s.lower() for s in required_skills]
            ]

            missing_skills = [
                skill
                for skill in required_skills
                if skill.lower() not in [s.lower() for s in candidate_skills]
            ]

            recommendation = (
                f"Matched {len(matched_skills)} of "
                f"{len(required_skills)} required skills."
            )

            results.append([
                profile.get("candidate_name",""),
                python_score,
                ", ".join(required_skills),
                ", ".join(candidate_skills),
                ", ".join(matched_skills),
                ", ".join(missing_skills),
                profile.get("experience",""),
                profile.get("education",""),
                recommendation,
                ai_result["fit_level"],
                ai_result["interview_decision"]
            ])

        except Exception as e:

            print(f"Error processing {resume.name}: {e}")

    df = pd.DataFrame(

        results,

        columns=[

            "Candidate",

            "Score",

            "Required Skills",

            "Candidate Skills",

            "Matched Skills",

            "Missing Skills",

            "Experience",

            "Education",

            "AI Recommendation",

            "Fit Level",

            "Interview Decision"

        ]

    )

    df = df.sort_values(

        by="Score",

        ascending=False

    )

    return df

In [88]:
import gradio as gr

with gr.Blocks(
    title="RecruitAI",
    theme=gr.themes.Soft()
) as demo:

    gr.Markdown("# 🤖 RecruitAI - Intelligent Recruitment Assistant")
    gr.Markdown(
        "Upload a Job Description and multiple resumes to evaluate, rank and shortlist candidates."
    )

    with gr.Row():

        jd_file = gr.File(
            label="📄 Upload Job Description"
        )

        resume_files = gr.File(
            label="📁 Upload Multiple Resumes",
            file_count="multiple"
        )

    evaluate_btn = gr.Button(
        "🚀 Evaluate Candidates",
        variant="primary"
    )

    gr.Markdown("## 📊 Candidate Ranking")

    results_table = gr.Dataframe(
        headers=[
            "Candidate",
            "Score",
            "Required Skills",
            "Candidate Skills",
            "Matched Skills",
            "Missing Skills",
            "Experience",
            "Education",
            "Current CTC",
            "Expected CTC",
            "Notice Period",
            "AI Recommendation",
            "Fit Level",
            "Interview Decision"
        ],
        interactive=False,
        wrap=True
    )

    evaluate_btn.click(
        fn=evaluate_pipeline,
        inputs=[
            jd_file,
            resume_files
        ],
        outputs=results_table
    )

demo.launch(debug=True)

/tmp/ipykernel_1970/2319094848.py:3: UserWarning: The parameters have been moved from the Blocks constructor to the launch() method in Gradio 6.0: theme. Please pass these parameters to launch() instead.
  with gr.Blocks(

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://de6bb5b2ce1c041757.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://de6bb5b2ce1c041757.gradio.live

In [88]:
import matplotlib.pyplot as plt
import os

os.makedirs("charts", exist_ok=True)

In [ ]:
import matplotlib.pyplot as plt
import os

os.makedirs("charts", exist_ok=True)

In [104]:
import pandas as pd
import matplotlib.pyplot as plt
import os

os.makedirs("charts", exist_ok=True)

def evaluate_pipeline(jd_file, resume_files):

    # --------------------------
    # Read JD
    # --------------------------
    with open(jd_file.name, "r", encoding="utf-8") as f:
        jd_text = f.read()

    jd_profile = parse_jd_with_groq(jd_text)
    required_skills = jd_profile.get("skills", [])

    candidates = []

    # --------------------------
    # Process Resumes
    # --------------------------
    for resume in resume_files:

        try:

            resume_text = extract_text_from_pdf(resume.name)

            profile = parse_resume_with_groq(resume_text)

            python_score, breakdown = calculate_score(
                jd_profile,
                profile
            )

            ai = evaluate_candidate(
                jd_profile,
                profile
            )

            candidate_skills = profile.get("skills", [])

            matched = [
                s for s in candidate_skills
                if s.lower() in [x.lower() for x in required_skills]
            ]

            missing = [
                s for s in required_skills
                if s.lower() not in [x.lower() for x in candidate_skills]
            ]

            candidates.append({

                "Candidate": profile.get("candidate_name", ""),
                "Score": python_score,
                "Matched Skills": matched,
                "Missing Skills": missing,
                "Education": profile.get("education", ""),
                "Experience": profile.get("experience", ""),
                "Decision": ai["interview_decision"],
                "Fit": ai["fit_level"]

            })

        except Exception as e:
            print("Resume Error:", e)

    # --------------------------
    # Sort Candidates
    # --------------------------
    candidates = sorted(
        candidates,
        key=lambda x: x["Score"],
        reverse=True
    )

    # --------------------------
    # Ranking Table
    # --------------------------
    ranking = []

    medals = ["🥇", "🥈", "🥉"]

    for i, c in enumerate(candidates):

        rank = medals[i] if i < 3 else str(i + 1)

        ranking.append([
            rank,
            c["Candidate"],
            c["Score"],
            c["Decision"]
        ])

    ranking_df = pd.DataFrame(
        ranking,
        columns=[
            "Rank",
            "Candidate",
            "Score",
            "Decision"
        ]
    )

    # --------------------------
    # Dashboard
    # --------------------------
    total = len(candidates)

    shortlisted = sum(
        x["Decision"].lower() == "shortlist"
        for x in candidates
    )

    hold = sum(
        x["Decision"].lower() == "hold"
        for x in candidates
    )

    rejected = total - shortlisted - hold

    highest = candidates[0]["Score"] if total else 0

    # --------------------------
    # Charts
    # --------------------------
    chart_path = None
    pie_chart_path = None

    if total > 0:

        # Bar Chart
        names = [c["Candidate"] for c in candidates]
        scores = [c["Score"] for c in candidates]

        plt.figure(figsize=(8, 4))
        plt.bar(names, scores)
        plt.title("Candidate Score Comparison")
        plt.xlabel("Candidates")
        plt.ylabel("Score")
        plt.xticks(rotation=30)
        plt.tight_layout()

        chart_path = "charts/score_chart.png"

        plt.savefig(chart_path)
        plt.close()

        # Pie Chart
        pie_chart_path = "charts/candidate_status.png"

        plt.figure(figsize=(5, 5))

        plt.pie(
            [shortlisted, hold, rejected],
            labels=["Shortlisted", "Hold", "Rejected"],
            autopct="%1.1f%%",
            startangle=90
        )

        plt.title("    Candidate Status Distribution")

        plt.savefig(
            pie_chart_path,
            bbox_inches="tight"
        )

        plt.close()
            # --------------------------
    # Candidate Card
    # --------------------------
    if total:

        top = candidates[0]

        candidate_card = f"""
# 👤 {top['Candidate']}

### ⭐ Score : **{top['Score']}**

### 🎓 Education

{top['Education']}

### 💼 Experience

{top['Experience']}

### 🟢 Matched Skills

{'<br>'.join('✅ ' + x for x in top['Matched Skills'])}

### 🔴 Missing Skills

{'<br>'.join('❌ ' + x for x in top['Missing Skills'])}
"""

        recommendation = f"""
## 🤖 AI Recommendation

**Fit Level:** {top['Fit']}

**Interview Decision:** {top['Decision']}

Matched **{len(top['Matched Skills'])}** required skills.

Missing **{len(top['Missing Skills'])}** required skills.

Proceed according to recruiter policy.
"""

    else:

        candidate_card = "No candidates found."

        recommendation = "No recommendation available."

    # --------------------------
    # Return Outputs
    # --------------------------
    return (
        ranking_df,
        total,
        shortlisted,
        hold,
        rejected,
        highest,
        candidate_card,
        recommendation,
        chart_path,
        pie_chart_path
    )

# Better UI

In [103]:
import gradio as gr

with gr.Blocks(
    title="RecruitAI - Intelligent Recruitment Assistant"
) as demo:

    # ==========================
    # Header
    # ==========================

    gr.Markdown("""
<div style='text-align:center;
padding:25px;
border-radius:20px;
background:linear-gradient(90deg,#4F46E5,#7C3AED);
color:white;
box-shadow:0px 4px 15px rgba(0,0,0,0.2);'>

<h1>🤖 RecruitAI</h1>

<h3>Intelligent Recruitment Assistant</h3>

<p>
Upload one Job Description and multiple resumes to automatically rank
candidates using AI + Python Scoring.
</p>

</div>
""")

    # ==========================
    # Upload Section
    # ==========================

    gr.Markdown("## 📂 Upload Documents")

    with gr.Row():

        jd_file = gr.File(
            label="📄 Job Description (.txt)",
            file_types=[".txt"]
        )

        resume_files = gr.File(
            label="📑 Candidate Resumes (.pdf)",
            file_types=[".pdf"],
            file_count="multiple"
        )

    evaluate_btn = gr.Button(
        "🚀 Evaluate Candidates",
        variant="primary",
        size="lg"
    )

    gr.Markdown("---")

    # ==========================
    # Dashboard
    # ==========================

    gr.Markdown("""
# 📊 Recruitment Dashboard

### AI Powered Hiring Analytics
""")

    with gr.Row():

        total_candidates = gr.Number(
            label="👥 Total Candidates",
            interactive=False
        )

        shortlisted = gr.Number(
            label="🟢 Shortlisted",
            interactive=False
        )

        hold = gr.Number(
            label="🟡 Hold",
            interactive=False
        )

        rejected = gr.Number(
            label="🔴 Rejected",
            interactive=False
        )

        highest_score = gr.Number(
            label="🏆 Highest Score",
            interactive=False
        )

    gr.Markdown("---")

    # ==========================
    # Ranking Table
    # ==========================

    gr.Markdown("## 🏅 Candidate Ranking")

    results_table = gr.Dataframe(
        headers=[
            "Rank",
            "Candidate",
            "Score",
            "Decision"
        ],
        interactive=False,
        wrap=True
    )

    gr.Markdown("---")

    # ==========================
    # Candidate Details
    # ==========================

    with gr.Row():

        with gr.Column(scale=1):

            gr.Markdown("""
# 👤 Candidate Profile

AI Generated Candidate Summary
""")

            candidate_card = gr.Markdown()

        with gr.Column(scale=1):

            gr.Markdown("""
# 🤖 AI Recommendation

Python Scoring + LLM Recommendation
""")

            recommendation_box = gr.Markdown()

    gr.Markdown("---")

    # ==========================
    # Analytics
    # ==========================

    gr.Markdown("# 📈 Candidate Analytics")

    with gr.Row():

        score_chart = gr.Image(
            label="📊 Candidate Score Comparison",
            type="filepath",
            interactive=False
        )

        pie_chart = gr.Image(
            label="🥧    Candidate Status Distribution",
            type="filepath",
            interactive=False
        )

    # ==========================
    # Button Action
    # ==========================

    evaluate_btn.click(
        fn=evaluate_pipeline,
        inputs=[
            jd_file,
            resume_files
        ],
        outputs=[
            results_table,
            total_candidates,
            shortlisted,
            hold,
            rejected,
            highest_score,
            candidate_card,
            recommendation_box,
            score_chart,
            pie_chart
        ]
    )

demo.launch(debug=True)

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://7c2a00ed9d07be7e96.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://7c2a00ed9d07be7e96.gradio.live